# JobManager configuration
jobmanager.memory.process.size: 1536m
jobmanager.rpc.address: jobmanager
jobmanager.rpc.port: 6123
rest.address: jobmanager
rest.port: 8081

# TaskManager configuration
taskmanager.memory.process.size: 4096m
taskmanager.memory.framework.heap.size: 512m
taskmanager.memory.jvm-metaspace.size: 256m
taskmanager.memory.jvm-overhead.min: 192m
taskmanager.memory.jvm-overhead.max: 1g
taskmanager.memory.network.min: 64m
taskmanager.memory.network.max: 128m
taskmanager.numberOfTaskSlots: 2
taskmanager.cpu.cores: 2
taskmanager.host: taskmanager
taskmanager.rpc.port: 6123

# # Kafka consumer configurations
# kafka.consumer.max.poll.interval.ms: 300000
# kafka.consumer.max.poll.records: 100
# kafka.consumer.fetch.max.wait.ms: 1000

# Parallelism and performance
parallelism.default: 2

# Metrics
metrics.reporter.slf4j.factory.class: org.apache.flink.metrics.slf4j.Slf4jReporterFactory
metrics.reporter.slf4j.interval: 10 SECONDS

# JVM options
env.java.opts: -XX:+IgnoreUnrecognizedVMOptions --illegal-access=permit -XX:+UseG1GC -XX:MaxGCPauseMillis=100
blob.server.port: 6124
query.server.port: 6125

jobmanager.rpc.address: jobmanager


jobmanager.rpc.address: jobmanager
taskmanager.numberOfTaskSlots: 2

jobmanager.rpc.address: jobmanager

jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
jobmanager.rpc.address: jobmanager
